// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVhDxzfeZFqkzcacY6VrCzaJcDi14zuDw',
    appId: '1:1042891968517:web:0a03408577c15ae0edcc6c',
    messagingSenderId: '1042891968517',
    projectId: 'smart-mart-81ebe',
    authDomain: 'smart-mart-81ebe.firebaseapp.com',
    storageBucket: 'smart-mart-81ebe.firebasestorage.app',
    measurementId: 'G-DFLY0Q10KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1ASh3eQVzapDbFZMntN5FfwCf9Jq6Qs4',
    appId: '1:1042891968517:android:78b0e97d6c6659b5edcc6c',
    messagingSenderId: '1042891968517',
    projectId: 'smart-mart-81ebe',
    storageBucket: 'smart-mart-81ebe.firebasestorage.app',
  );

}